### ISSUE TITLE
 /api/v1/user/create says user_proxy_config or proxyid is required when proxyid is provided 

### ISSUE THREAD

**Issue by tatumsu** [AdsPower/localAPI#2]
When request /api/v1/user/create with following code:
        payload = {
            "name": "TEST-1",
            "group_id": "193511",
            "proxyid": "41",
            "remark": remark,
            "fingerprint_config": {
                "timezone": "Asia/Shanghai",
                "language": ["zh-CN", "en-US", "en"],
                "flash": "block",
                "fonts": ["all"],
                "webrtc": "disabled",
            },
        }
        headers = {
            'Content-Type': 'application/json'
        }
        resp = requests.request("POST", url=url, headers=headers, json=payload)

the api returns error as following:
b'{"data":{},"msg":"user_proxy_config or proxyid is required","code":1002}'

according to the document, proxyid should be enough if provided.

**Comment by mffseal** [comment]
same issue, "proxyid" not work.
