### ISSUE TITLE
user/regroup, error 1500

### ISSUE THREAD

**Issue by tyhja-mitaton** [AdsPower/localAPI#3]
I'm getting error "Invalid request" when trying to change account's group. I seemingly did everything in accordance with documentation. My request is as following: https://i.imgur.com/YPX9khd.png

**Comment by maksqi** [comment]
![image](https://user-images.githubusercontent.com/63323631/225531948-3bb6fa28-440b-4ab0-aa6c-ca47a6cb3341.png)

I have the same problem, tried everything

**Comment by AdsPower** [comment]
The content format of POST should be JSON.
![image](https://user-images.githubusercontent.com/101709438/226545239-c6bf3483-7768-48ba-b6bd-b88bb0938be2.png)
