### ISSUE TITLE
Endpoint for getting currently active browsers

### ISSUE THREAD

**Issue by m1ronow** [AdsPower/localAPI#4]
Can we get an endpoint for getting currently active browsers? Or as an alternative - add isActive field to returning data in /api/v1/user/list endpoint. There is no possible way to get that info programmatically (except sending requests to /api/v1/browser/active one by one, which is obviously the worst and the slowest way), although it is possible to do it in UI, so I guess it is possible to implement the feature in API

**Comment by AdsPower** [comment]
/api/v1/browser/local-active 
is show all active
[Local Api Doc](https://localapi-doc-zh.adspower.net/docs/SWZF3h#9e5ffa068ed435ced73dc9bf5dd8e09c_3)
