### ISSUE TITLE
Is there any way to connect the launch browser with puppeteer or playwright?

### ISSUE THREAD

**Issue by MdRonyAhmed** [AdsPower/localAPI#5]

**Comment by roman-ponomarenko** [comment]
Yes, there's a way for Playwright
`const browser = await chromium.connectOverCDP(
    'ws://127.0.0.1:50863/devtools/browser/5b92c0d3-4c69-4138-b7ad-7359ceb85c73',
    {slowMo: 10}
  )
  const context = browser.contexts()[0];
  console.log(`Context sizes - ${browser.contexts().length}`);
  console.log(`Pages sizes - ${context.pages().length}`);`

**Comment by AdsPower** [comment]
AdsPower Local Api Playwright Demo:

```javascript
const axios = require('axios');
const { chromium } = require('playwright');

axios.get('http://local.adspower.net:50325/api/v1/browser/start?user_id=xxxx').then(async (res) => {
  if (res.data.code === 0 && res.data.data.ws && res.data.data.ws.puppeteer) {
      const browser = await chromium.connectOverCDP(res.data.data.ws.puppeteer);
      const defaultContext = browser.contexts()[0];
      const page = await defaultContext.newPage();
      await page.goto('https://www.adspower.net');
      await page.screenshot({ path: './adspower.png', fullPage: true });
      await browser.close();
  }
}).catch((err) => {
	console.log(err)
});
```


AdsPower Local Api Puppeteer Demo:

[https://github.com/AdsPower/localAPI/blob/main/js-examples/example-start-profile.js](https://github.com/AdsPower/localAPI/blob/main/js-examples/example-start-profile.js)
